### ISSUE TITLE
작업한 코드 하나의 클래스로 통합

### ISSUE THREAD

**Issue by sijbwer77** [Nhh05/oss_data_library#3]
현재 각각의 폴더에서 작업한 파일들이 분리되어 있습니다.

각자 branch에 작업해놓은 파일들을 해석하고, 클래스로 만들 계획입니다.

작업할 내용
1. 각자 코드 설명하는 주석 추가
2. 폴더별 파일, 기능 함수화(메서드화) -> 개별 진행
3. 클래스 설계, 코드작성

**Comment by gitleejm** [comment]
알겠습니당

**Comment by sijbwer77** [comment]
**내일 회의 전까지 1번, 2번 완료해놓기**
